# Generated by Django 3.1.3 on 2020-11-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandlerApp', '0003_newmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('collections', models.JSONField()),
            ],
        ),
    ]
