# Generated by Django 3.1.3 on 2020-11-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandlerApp', '0004_final_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='aimapsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'aimaps',
            },
        ),
        migrations.DeleteModel(
            name='demo2Model',
        ),
        migrations.DeleteModel(
            name='demoModels',
        ),
        migrations.DeleteModel(
            name='final_model',
        ),
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
