# Generated by Django 3.1.3 on 2020-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandlerApp', '0005_auto_20201119_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimapsmodels',
            name='item',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
